name: Build FairTech-AIO-Updater

on: 
  push:
  workflow_dispatch:

jobs:
  FairTech-AIO-Updater:
    runs-on: ubuntu-latest
    #container: hamletdufromage/devkita64_devkitarm
    container: devkitpro/devkita64
    steps:
    - uses: actions/checkout@v1

    - name: update repo
      run: |
        git submodule update --init --recursive
        
    - name: Building FairTech-AIO-Updater
      run: |
        make -C aiosu-forwarder -f Makefile
        make -j$(nproc)
        
    - uses: actions/upload-artifact@master
      with:
        name: FairTech-AIO-Updater
        path: FairTech-AIO-Updater.nro
